language: python
python:
  - "3.6"

before_script: 	pip install -r requirements.txt

#script: - main/Client/start_client
deploy:
  provider: script
  script: bash main/Client/start_client.sh
  on:
    branch: main
